# Generated by Django 3.1.6 on 2021-02-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=100)),
                ('scontact', models.CharField(max_length=15)),
                ('sdeksripsi_keluhan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
